modules:
  http_hello_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: [ "HTTP/1.1", "HTTP/2" ]
      valid_status_codes: [200]
      method: GET
      headers:
        Host: "localhost"      
      fail_if_body_not_matches_regexp:
        - "Hello"
