global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus server itself

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] # Node exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] # Redis exporter

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187'] # Postgres exporter

  - job_name: 'rails'
    static_configs:
      - targets: ['web:3000'] # Rails APM

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_hello_2xx]
    static_configs:
      - targets:
          - http://web:3000/ # Target to probe (syntetic monitoring)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115